### ISSUE TITLE
Task compeleted 

### ISSUE THREAD

**Issue by deependra227** [gsunit/Flutter-Preliminary-Tasks#1]
### Instructions
- [x] Fork this repo.
- [x] Install Flutter on your laptop.
- [x] Create and run a new app (either using an emulator, or in your own device).
- [x] Upload the contents of the app on your forked Github repository.
- [x] Create a new issue on the [original repo](https://github.com/gsunit/Flutter-Preliminary-Tasks/issues). Copy the contents of this README and paste it inside the issue so that you can tick the tasks that you have completed.
- [x] Start working on the app.

### Useful suggestions
- You might want to learn the basics of `git` first if you don't know it already.
- I'll be checking the progress in the issues, so keep checking the items in `Instructions`, `Task Description` & `Reading Material` as you complete them.
- <strong> It is not necessary to complete all the tasks. </strong> Complete as many as you can.
- The links to the resources in the `Reading Material` sections are just suggestions. All that matters is that you are familiar with the mentioned topics. Feel free to Google the topics on your own (which I recommend) and, say, read a `Medium` article instead.
- You can contact me, Sunit Gautam, or Anish Saxena if you face any problems.

### Task description
- [x] Link a new Firebase Project with your Flutter app.
- [x] Setup Google Sign-In in your app.
- [x] Feed data into `Firestore` and display in app using `StreamBuilder` widget.
- [x]  Store user's `Name`, `Profile Pic`, `Email ID` in a `users` document in `Firestore`& create a basic profile page displaying the stored info.

### Reading Material
- [x] Flutter basics, you can refer to [MtechViral](<https://www.youtube.com/watch?v=qWL1lGchpRA&list=PLR2qQy0Zxs_UdqAcaipPR3CG1Ly57UlhV>),  [RajaYogan](https://www.youtube.com/watch?v=8li-NNipShI&list=PLgGjX33Qsw-EMsLf8TmsYhKOCx2ALZiKi) or multiple others available on the net to cover these topics
- [x]  `Stateless` vs `Stateful` widgets
- [x]  `Scaffold` to create a page
- [x]  Creating UI in Flutter ([Official Flutter UI tutorial](https://flutter.dev/docs/development/ui/layout/tutorial), [YouTube playlist](https://www.youtube.com/watch?v=VE1IsV0HABs&list=PLgGjX33Qsw-FIWxoI2IJf7zsHyxzuFfK5))
- [x] `Firebase Auth` and `Firestore CRUD Operation` ([Firestore Tutorial](https://www.youtube.com/watch?v=LzEbpALmRlc&list=PLgGjX33Qsw-Ha_8ks9im86sLIihimuYrr))
- [x] Using streams to make dynamic lists [Tensor Programming](https://www.youtube.com/watch?v=hvvYA1N-tEc&list=PLJbE2Yu2zumDqr_-hqpAN0nIr6m14TAsd&index=4&t=0s)
